import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HamBurgerMenu } from "@/components/component/nav-menu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-screen">
          <HamBurgerMenu />
          {children}
        </main>
      </body>
    </html>
  );
}
